### ISSUE TITLE
Occluded-REID数据集

### ISSUE THREAD

**Issue by ghost** [littleprince1121/PADE#2]
作者您好，我想请教一下您的实验中Occluded-REID数据集是如何组织的呢？是将他们随机划分成query和gallery吗？

**Comment by ziwang1121** [comment]
您好，这个数据集公开的数据里就分好了query跟gallery，我按照文件夹的设置来测试的。query都是遮挡的图像，gallery都是全身图像。我使用的数据集链接（训练集是Market1501）：https://drive.google.com/file/d/1WTS_2kz5NyJztQaMvjFdlmg9VzMGv_gp/view?usp=drive_link

**Comment by ghost** [comment]
> 您好，这个数据集公开的数据里就分好了query跟gallery，我按照文件夹的设置来测试的。query都是遮挡的图像，gallery都是全身图像。我使用的数据集链接（训练集是Market1501）：https://drive.google.com/file/d/1WTS_2kz5NyJztQaMvjFdlmg9VzMGv_gp/view?usp=drive_link

感谢您的解答！

**Comment by liudongcan666** [comment]
![Uploading 5}1[Q3DMJ1Z@~)M0SEG}NUL.png…]()
你好，请问Occluded-REID的数据为什么训练不起来，make_dataloader文件报错我也修改了

**Comment by liudongcan666** [comment]
/home/liudongcan/桌面/ldc/PADE/utils/metrics.py:12: UserWarning: This overload of addmm_ is deprecated:
        addmm_(Number beta, Number alpha, Tensor mat1, Tensor mat2)
Consider using one of the following signatures instead:
        addmm_(Tensor mat1, Tensor mat2, *, Number beta, Number alpha) (Triggered internally at ../torch/csrc/utils/python_arg_parser.cpp:1578.)
  dist_mat.addmm_(1, -2, qf, gf.t())
Note: number of gallery samples is quite small, got 14
Traceback (most recent call last):
  File "/home/liudongcan/桌面/ldc/PADE/train.py", line 78, in <module>
    do_train(
  File "/home/liudongcan/桌面/ldc/PADE/processor/processor.py", line 139, in do_train
    cmc, mAP, _, _, _, _, _ = evaluator.compute()
  File "/home/liudongcan/桌面/ldc/PADE/utils/metrics.py", line 131, in compute
    cmc, mAP = eval_func(distmat, q_pids, g_pids, q_camids, g_camids)
  File "/home/liudongcan/桌面/ldc/PADE/utils/metrics.py", line 81, in eval_func
    assert num_valid_q > 0, "Error: all query identities do not appear in gallery"
AssertionError: Error: all query identities do not appear in gallery

**Comment by ziwang1121** [comment]
> /home/liudongcan/桌面/ldc/PADE/utils/metrics.py:12: UserWarning: This overload of addmm_ is deprecated: addmm_(Number beta, Number alpha, Tensor mat1, Tensor mat2) Consider using one of the following signatures instead: addmm_(Tensor mat1, Tensor mat2, *, Number beta, Number alpha) (Triggered internally at ../torch/csrc/utils/python_arg_parser.cpp:1578.) dist_mat.addmm_(1, -2, qf, gf.t()) Note: number of gallery samples is quite small, got 14 Traceback (most recent call last): File "/home/liudongcan/桌面/ldc/PADE/train.py", line 78, in do_train( File "/home/liudongcan/桌面/ldc/PADE/processor/processor.py", line 139, in do_train cmc, mAP, _, _, _, _, _ = evaluator.compute() File "/home/liudongcan/桌面/ldc/PADE/utils/metrics.py", line 131, in compute cmc, mAP = eval_func(distmat, q_pids, g_pids, q_camids, g_camids) File "/home/liudongcan/桌面/ldc/PADE/utils/metrics.py", line 81, in eval_func assert num_valid_q > 0, "Error: all query identities do not appear in gallery" AssertionError: Error: all query identities do not appear in gallery

我下载里这个项目的代码在本地进行了训练与测试，只需要将“./datasets/make_dataloader.py”的16、17与26、27行的注释取消掉，然后按照教程的指令运行就可以了。并没有出现你说的这个错误，你可以看看我回复你的邮件，查看一下错误来源。

**Comment by ziwang1121** [comment]
> > /home/liudongcan/桌面/ldc/PADE/utils/metrics.py:12: UserWarning: This overload of addmm_ is deprecated: addmm_(Number beta, Number alpha, Tensor mat1, Tensor mat2) Consider using one of the following signatures instead: addmm_(Tensor mat1, Tensor mat2, *, Number beta, Number alpha) (Triggered internally at ../torch/csrc/utils/python_arg_parser.cpp:1578.) dist_mat.addmm_(1, -2, qf, gf.t()) Note: number of gallery samples is quite small, got 14 Traceback (most recent call last): File "/home/liudongcan/桌面/ldc/PADE/train.py", line 78, in do_train( File "/home/liudongcan/桌面/ldc/PADE/processor/processor.py", line 139, in do_train cmc, mAP, _, _, _, _, _ = evaluator.compute() File "/home/liudongcan/桌面/ldc/PADE/utils/metrics.py", line 131, in compute cmc, mAP = eval_func(distmat, q_pids, g_pids, q_camids, g_camids) File "/home/liudongcan/桌面/ldc/PADE/utils/metrics.py", line 81, in eval_func assert num_valid_q > 0, "Error: all query identities do not appear in gallery" AssertionError: Error: all query identities do not appear in gallery
> 
> 我下载里这个项目的代码在本地进行了训练与测试，只需要将“./datasets/make_dataloader.py”的16、17与26、27行的注释取消掉，然后按照教程的指令运行就可以了。并没有出现你说的这个错误，你可以看看我回复你的邮件，查看一下错误来源。

看了你最新的邮件，应该是数据问题。你把前面的数据集重新下载解压一下，query跟gallery文件夹里应该都是1000张照片才对。

**Comment by zhouxingxing1024** [comment]
感谢，这个没注意，学长我这篇发了的话，给你个红包请你吃饭，我第二篇准备在你的Heterogeneous Test-Time Training for Multi-Modal Person Re-identification改动
&nbsp;


风吹裤衩凉
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Z. ***@***.***&gt;; 
发送时间: 2024年8月4日(星期天) 上午10:51
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ziwang1121/PADE] Occluded-REID数据集 (Issue #2)














   
/home/liudongcan/桌面/ldc/PADE/utils/metrics.py:12: UserWarning: This overload of addmm_ is deprecated: addmm_(Number beta, Number alpha, Tensor mat1, Tensor mat2) Consider using one of the following signatures instead: addmm_(Tensor mat1, Tensor mat2, *, Number beta, Number alpha) (Triggered internally at ../torch/csrc/utils/python_arg_parser.cpp:1578.) dist_mat.addmm_(1, -2, qf, gf.t()) Note: number of gallery samples is quite small, got 14 Traceback (most recent call last): File "/home/liudongcan/桌面/ldc/PADE/train.py", line 78, in do_train( File "/home/liudongcan/桌面/ldc/PADE/processor/processor.py", line 139, in do_train cmc, mAP, _, _, _, _, _ = evaluator.compute() File "/home/liudongcan/桌面/ldc/PADE/utils/metrics.py", line 131, in compute cmc, mAP = eval_func(distmat, q_pids, g_pids, q_camids, g_camids) File "/home/liudongcan/桌面/ldc/PADE/utils/metrics.py", line 81, in eval_func assert num_valid_q &gt; 0, "Error: all query identities do not appear in gallery" AssertionError: Error: all query identities do not appear in gallery
  
我下载里这个项目的代码在本地进行了训练与测试，只需要将“./datasets/make_dataloader.py”的16、17与26、27行的注释取消掉，然后按照教程的指令运行就可以了。并没有出现你说的这个错误，你可以看看我回复你的邮件，查看一下错误来源。
  
看了你最新的邮件，应该是数据问题。你把前面的数据集重新下载解压一下，query跟gallery文件夹里应该都是1000张照片才对。
